#!/bin/bash
# https://www.linkedin.com/pulse/fixing-maven-build-issues-claude-code-web-ccw-tarun-lalwani-8n7oc/
set -uxo pipefail

# Only run in Claude Code on the web (remote environment)
if [ "${CLAUDE_CODE_REMOTE:-}" != "true" ]; then
  exit 0
fi

echo "Configuring Gradle for Claude Code remote environment..."

# Create Gradle config directory
mkdir -p ~/.gradle

# Extract proxy host, port, and authentication from HTTPS_PROXY environment variable
# Expected format: http://user:pass@host:port
if [ -n "${HTTPS_PROXY:-}" ]; then
  # Remove protocol prefix
  PROXY_URL_NO_PROTO=$(echo "$HTTPS_PROXY" | sed -E 's|https?://||')

  # Extract authentication part (everything before @)
  AUTH_PART=$(echo "$PROXY_URL_NO_PROTO" | cut -d'@' -f1)
  PROXY_USER=$(echo "$AUTH_PART" | cut -d':' -f1)
  PROXY_PASS=$(echo "$AUTH_PART" | cut -d':' -f2-)

  # Extract host and port from proxy URL
  PROXY_HOST=$(echo "$HTTPS_PROXY" | sed -E 's|https?://([^:@]*:)?([^:@]*)@||' | sed -E 's|https?://||' | cut -d':' -f1)
  PROXY_PORT=$(echo "$HTTPS_PROXY" | sed -E 's|https?://([^:@]*:)?([^:@]*)@||' | sed -E 's|https?://||' | cut -d':' -f2 | cut -d'/' -f1)

  echo "Detected proxy: $PROXY_HOST:$PROXY_PORT (with authentication)"

  # Get no_proxy list and convert to pipe-separated format (Java expects pipes, not commas)
  NO_PROXY_HOSTS_COMMA="${NO_PROXY:-localhost,127.0.0.1}"
  NO_PROXY_HOSTS=$(echo "$NO_PROXY_HOSTS_COMMA" | tr ',' '|')

  # Create Gradle gradle.properties with proxy configuration including authentication
  cat > ~/.gradle/gradle.properties <<EOF
# Auto-generated by Claude Code Web session start hook
# Proxy configuration for Gradle

systemProp.http.proxyHost=${PROXY_HOST}
systemProp.http.proxyPort=${PROXY_PORT}
systemProp.http.proxyUser=${PROXY_USER}
systemProp.http.proxyPassword=${PROXY_PASS}
systemProp.http.nonProxyHosts=${NO_PROXY_HOSTS}

systemProp.https.proxyHost=${PROXY_HOST}
systemProp.https.proxyPort=${PROXY_PORT}
systemProp.https.proxyUser=${PROXY_USER}
systemProp.https.proxyPassword=${PROXY_PASS}
systemProp.https.nonProxyHosts=${NO_PROXY_HOSTS}

# Gradle daemon configuration
org.gradle.daemon=true
org.gradle.parallel=false
org.gradle.caching=true
EOF

  # Create init.gradle for proxy authentication (Java Authenticator setup)
  cat > ~/.gradle/init.gradle <<'INITSCRIPT'
import java.net.Authenticator
import java.net.PasswordAuthentication

// Set up proxy authenticator for authenticated proxies in Claude Code Web
def proxyUser = System.getProperty('http.proxyUser')
def proxyPass = System.getProperty('http.proxyPassword')

if (proxyUser && proxyPass) {
    Authenticator.setDefault(new Authenticator() {
        @Override
        protected PasswordAuthentication getPasswordAuthentication() {
            if (getRequestorType() == RequestorType.PROXY) {
                return new PasswordAuthentication(proxyUser, proxyPass.toCharArray())
            }
            return null
        }
    })
    println "✅ Configured proxy authenticator for Claude Code Web"
}
INITSCRIPT

  echo "✅ Gradle gradle.properties and init.gradle created with proxy configuration"
else
  echo "⚠️  No HTTPS_PROXY environment variable found, skipping proxy configuration"
fi

echo "Session start hook completed successfully"