#!/bin/bash
# https://www.linkedin.com/pulse/fixing-maven-build-issues-claude-code-web-ccw-tarun-lalwani-8n7oc/
set -uxo pipefail

# Only run in Claude Code on the web (remote environment)
if [ "${CLAUDE_CODE_REMOTE:-}" != "true" ]; then
  exit 0
fi

echo "Configuring Gradle for Claude Code remote environment..."

# Create Gradle config directory
mkdir -p ~/.gradle

# Extract proxy host and port from HTTPS_PROXY environment variable
# Expected format: http://user:pass@host:port or http://host:port
if [ -n "${HTTPS_PROXY:-}" ]; then
  # Extract host and port from proxy URL
  PROXY_HOST=$(echo "$HTTPS_PROXY" | sed -E 's|https?://([^:@]*:)?([^:@]*)@||' | sed -E 's|https?://||' | cut -d':' -f1)
  PROXY_PORT=$(echo "$HTTPS_PROXY" | sed -E 's|https?://([^:@]*:)?([^:@]*)@||' | sed -E 's|https?://||' | cut -d':' -f2 | cut -d'/' -f1)

  echo "Detected proxy: $PROXY_HOST:$PROXY_PORT"

  # Get no_proxy list
  NO_PROXY_HOSTS="${NO_PROXY:-localhost|127.0.0.1}"

  # Create Gradle gradle.properties with proxy configuration
  cat > ~/.gradle/gradle.properties <<EOF
# Auto-generated by Claude Code Web session start hook
# Proxy configuration for Gradle

systemProp.http.proxyHost=${PROXY_HOST}
systemProp.http.proxyPort=${PROXY_PORT}
systemProp.http.nonProxyHosts=${NO_PROXY_HOSTS}

systemProp.https.proxyHost=${PROXY_HOST}
systemProp.https.proxyPort=${PROXY_PORT}
systemProp.https.nonProxyHosts=${NO_PROXY_HOSTS}

# Gradle daemon configuration
org.gradle.daemon=true
org.gradle.parallel=false
org.gradle.caching=true
EOF

  echo "✅ Gradle gradle.properties created with proxy configuration"
else
  echo "⚠️  No HTTPS_PROXY environment variable found, skipping proxy configuration"
fi

echo "Session start hook completed successfully"