/**
 * Provides version information for the application.
 * Reads from git.properties generated by gradle-git-properties plugin at build time.
 */
class VersionInfo {

    private static final String REPO_URL = 'https://github.com/JonasPammer/Vibed-ReadSignsAndBooks.jar'
    private static final String PROPERTIES_FILE = '/git.properties'

    private static Properties props = null

    /** Load git properties from classpath resource. */
    private static synchronized Properties getProperties() {
        if (props == null) {
            props = new Properties()
            try {
                def stream = VersionInfo.class.getResourceAsStream(PROPERTIES_FILE)
                if (stream) {
                    props.load(stream)
                    stream.close()
                }
            } catch (Exception e) {
                // Silently use defaults if properties file not found
            }
        }
        return props
    }

    /** Get the git commit hash (short form, e.g., "abc1234") */
    static String getCommitHash() {
        return getProperties().getProperty('git.commit.id.abbrev', 'unknown')
    }

    /** Get the commit date (e.g., "2025-12-22") */
    static String getCommitDate() {
        return getProperties().getProperty('git.commit.time', 'unknown')
    }

    /** Get the build date (e.g., "2025-12-22") */
    static String getBuildDate() {
        return getProperties().getProperty('git.build.time', 'unknown')
    }

    /** Get the repository URL */
    static String getRepoUrl() {
        // Prefer git.remote.origin.url if available, fallback to constant
        String url = getProperties().getProperty('git.remote.origin.url', REPO_URL)
        // Clean up SSH URLs to HTTPS format for browser
        if (url.startsWith('git@github.com:')) {
            url = url.replace('git@github.com:', 'https://github.com/')
        }
        if (url.endsWith('.git')) {
            url = url[0..-5]
        }
        return url
    }

    /** Get the URL to view a specific commit on GitHub */
    static String getCommitUrl() {
        String hash = getCommitHash()
        if (hash == 'unknown') {
            return getRepoUrl()
        }
        return "${getRepoUrl()}/commit/${hash}"
    }

    /** Get formatted version string for display (e.g., "abc1234 (2025-12-22)") */
    static String getFullVersionString() {
        String hash = getCommitHash()
        String date = getCommitDate()
        if (hash == 'unknown') {
            return 'dev'
        }
        return "${hash} (${date})"
    }

    /** Get version info formatted for CLI --version output (multi-line) */
    static String[] getVersionLines() {
        return [
            "ReadSignsAndBooks ${getFullVersionString()}",
            "Commit: ${getCommitUrl()}",
            "Built: ${getBuildDate()}"
        ] as String[]
    }
}
